import { Spell } from '@/types/character';

// Use import.meta.env.BASE_URL to get the correct base path (works with GitHub Pages)
const BUNDLED_SPELLS_PATH = `${import.meta.env.BASE_URL}data/spells.json`;

// MS5: Spell database loaded from JSON (generated by scripts/parse-spells.ts)
// This will be populated by loadSpellDatabase()
let spellDatabase: Spell[] = [];
let spellDatabaseLoaded = false;

// Cache configuration (matches perks cache duration)
const SPELL_CACHE_KEY = 'exceed-spells-cache';
const CACHE_DURATION_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

interface SpellDatabaseJSON {
  version: string;
  lastUpdated: number;
  spells: Spell[];
}

interface SpellCache {
  database: SpellDatabaseJSON;
  timestamp: number;
  expiresAt: number;
  version: string;  // Track the spells.json version
  lastUpdated: number;  // Track the spells.json lastUpdated timestamp
}

/**
 * Get cached spells from localStorage
 * Returns null if cache is expired or if spells.json has been updated (version/lastUpdated mismatch)
 */
function getCachedSpells(): Spell[] | null {
  try {
    const cacheStr = localStorage.getItem(SPELL_CACHE_KEY);
    if (!cacheStr) return null;

    const cache: SpellCache = JSON.parse(cacheStr);

    // Check if cache is expired
    if (Date.now() > cache.expiresAt) {
      localStorage.removeItem(SPELL_CACHE_KEY);
      console.log('[SpellLoader] Cache expired');
      return null;
    }

    // Check if we have a version/lastUpdated mismatch (build updated spells.json)
    // This happens when the build runs and generates new data
    const currentVersion = cache.database.version;
    const currentLastUpdated = cache.database.lastUpdated;

    // If the stored version/lastUpdated doesn't match what's in cache, invalidate
    if (cache.version !== currentVersion || cache.lastUpdated !== currentLastUpdated) {
      localStorage.removeItem(SPELL_CACHE_KEY);
      console.log('[SpellLoader] Cache version mismatch, invalidating');
      return null;
    }

    console.log('[SpellLoader] Using cached spells from localStorage');
    return cache.database.spells;
  } catch (error) {
    console.error('[SpellLoader] Error reading cache:', error);
    return null;
  }
}

/**
 * Save spells to cache
 */
function cacheSpells(database: SpellDatabaseJSON): void {
  try {
    const cache: SpellCache = {
      database,
      timestamp: Date.now(),
      expiresAt: Date.now() + CACHE_DURATION_MS,
      version: database.version,
      lastUpdated: database.lastUpdated,
    };

    localStorage.setItem(SPELL_CACHE_KEY, JSON.stringify(cache));
    console.log('[SpellLoader] Cached spells in localStorage');
  } catch (error) {
    console.error('[SpellLoader] Error caching spells:', error);
  }
}

/**
 * Load the spell database from JSON file with cache fallback
 * Should be called at app startup
 */
export async function loadSpellDatabase(): Promise<void> {
  if (spellDatabaseLoaded) return;

  // Try cache first
  const cached = getCachedSpells();
  if (cached) {
    spellDatabase = cached;
    spellDatabaseLoaded = true;
    return;
  }

  // Load from bundled file
  try {
    console.log('[SpellLoader] Fetching spells from:', BUNDLED_SPELLS_PATH);
    const response = await fetch(BUNDLED_SPELLS_PATH);
    if (!response.ok) {
      throw new Error(`Failed to load spells.json: ${response.status} ${response.statusText}`);
    }
    const data: SpellDatabaseJSON = await response.json();
    spellDatabase = data.spells;
    spellDatabaseLoaded = true;

    // Cache the results
    cacheSpells(data);

    console.log(`[SpellLoader] Loaded ${spellDatabase.length} spells from database`);
  } catch (error) {
    console.error('[SpellLoader] Error loading spell database:', error);
    // Fallback to empty - app can still function with custom spells
    spellDatabase = [];
    spellDatabaseLoaded = true;
  }
}

/**
 * Clear spell cache (for debugging/testing)
 */
export function clearSpellCache(): void {
  localStorage.removeItem(SPELL_CACHE_KEY);
  console.log('[SpellLoader] Cache cleared');
}

/**
 * Get all spells from the database
 */
export function getAllSpells(): Spell[] {
  return spellDatabase;
}

/**
 * Get a spell by name
 */
export function getSpellByName(name: string): Spell | undefined {
  return spellDatabase.find(s => s.name === name);
}

/**
 * Get a spell by ID
 */
export function getSpellById(id: string): Spell | undefined {
  return spellDatabase.find(s => s.id === id);
}

/**
 * Get spells filtered by tier
 */
export function getSpellsByTier(tier: number): Spell[] {
  return spellDatabase.filter(s => s.tier === tier);
}

/**
 * Check if the spell database has been loaded
 */
export function isSpellDatabaseLoaded(): boolean {
  return spellDatabaseLoaded;
}

/**
 * Get the limit cost from spell data
 */
export function getLimitCostFromSpell(spell: Spell): number {
  return typeof spell.limitCost === 'number' ? spell.limitCost : 0;
}

// XP costs for learning spells by tier (using basic costs only)
export const SPELL_XP_COSTS: Record<number, number> = {
  0: 1,
  1: 3,
  2: 5,
  3: 7,
  4: 10,
  5: 15
};

// Spellcraft progression XP requirements (follows attribute pricing)
export const SPELLCRAFT_XP_REQUIREMENTS: Record<number, number> = {
  0: 0,    // Starting level
  1: 5,    // 5 XP to reach level 1
  2: 15,   // +10 XP (total 15)
  3: 30,   // +15 XP (total 30)
  4: 50,   // +20 XP (total 50)
  5: 75    // +25 XP (total 75)
};
